### PR TITLE
BRITECH-131: Introduce Serilog to replace printfn

### PR DESCRIPTION
**Pull request by csscottlogic**

### CODE REVIEW

**Comment by jebbinSCL** [comment]
It looks like there is a missing file? Speakers.Logging is in the project file, and the setupLogging() call in Program isn't defined.

**Comment by csscottlogic** [comment]
Good spot @jebbinSCL . I amended the commit to include Speakers/Logging.fs. Thanks.

**Comment by jebbinSCL** [comment]
:shipit:

**Comment by dwybourn** [comment]
:shipit: after fixing merge conflicts.

**Pull request merged**
