### PR TITLE
Rename speakers endpoint

### PR DESCRIPTION
**Pull request by thullSL**
This is just renaming the endpoint to `/sessions`. Functionally nothing has changed here, the objects returned are the old/wrong ones. Just the renaming of all the things.

@csscottlogic before this is merged can you rename this repo sessions? I don't have permission.

### CODE REVIEW

**Comment by jebbinSCL** [comment]
In the assemblyInfo.fs for speaker comms, we explicitly set the assembly copyright to "". I assume we want to do the same here.

**Comment by jebbinSCL** [comment]
It looks like there is a docker file at the root of the directory that still points to Speakers.exe instead of Session

**Comment by thullSL** [comment]
Both addressed in the that there push 1e71d3a

**Comment by jebbinSCL** [comment]
:shipit:

**Comment by ianlovell** [comment]
:shipit:

**Pull request merged**
